const TOOL_PEN = 'TOOL_PEN';
const TOOL_SCRIBBLE_PALLET = 'TOOL_SCRIBBLE_PALLET';
const TOOL_BRUSH_SIZE = 'TOOL_BRUSH_SIZE';
const TOOL_BRUSH_COLOR = 'TOOL_BRUSH_COLOR';
const TOOL_UNDO = 'TOOL_UNDO';
const TOOL_REDO = 'TOOL_REDO';
const TOOL_ERASER = 'TOOL_ERASER';

module.exports = {
  TOOL_PEN,
  TOOL_SCRIBBLE_PALLET,
  TOOL_BRUSH_SIZE,
  TOOL_BRUSH_COLOR,
  TOOL_UNDO,
  TOOL_REDO,
  TOOL_ERASER
}